### PR TITLE
Add option for custom headers

### PR DESCRIPTION
**Pull request by klizas**

### CODE REVIEW

**Comment by Brunty** [comment]
@klizas thanks for this! I like this idea 👍 

Can you document it in the `README`?

**Comment by klizas** [comment]
Thank you! I've updated README.

**Comment by Brunty** [comment]
Sorry for the delay on merging, thanks for this! :D

**Comment by klizas** [comment]
I'm glad to contribute this project. Can you tag new version? :)

**Comment by Brunty** [comment]
@klizas I need to add some tests for this, then I'll tag it - I'll try to get that done today (last week at work, so I'm a little busy at the minute, sorry!) <3

**Comment by Brunty** [comment]
@klizas tagged `1.11.0`

**Comment by klizas** [comment]
Thank you!

**Pull request merged**
