### PR TITLE
Fixed type problems from Psalm level 2 - dont forget to follow spabby…

### PR DESCRIPTION
**Pull request by GeeH**
… at twitch.tv

### CODE REVIEW

**Comment by Brunty** [comment]
Thanks for this! Will take a look over it later on :)

**Comment by Brunty** [comment]
Can this be added to travis so it runs in CI too?

**Comment by GeeH** [comment]
I guess, do you want me to make that change as part of this PR?

**Comment by GeeH** [comment]
@Brunty can't run as part of CI as Psalm depends on PHP 7.1 and therefore the 7.0 build fails. Would you be interested in PR that bumps to 7.3?

**Pull request closed without merging**
